### ISSUE TITLE
Cannot find the dataset

### ISSUE THREAD

**Issue by ssdred1250** [Frankluox/FewShotPL#11]
Hi, I'm trying to re-implement the COSOC, but I don't know how to get the following datasets.
One is "miniImageNet_contra" for pretraining Exemplar, and the other is the "miniImageNet_prob_crop" for training COSOC.
Are these different from miniImageNet? Or is it okay to use miniImageNet?

I'd really appreciate it if you could answer!

**Comment by Frankluox** [comment]
They are all paired with miniImageNet, just with different ways of processing data (different transformations and get_item functions). Feel free to use them with miniImageNet.
