### ISSUE TITLE
Problem when reproducing Meta-baseline

### ISSUE THREAD

**Issue by LIUZIJING-CHN** [Frankluox/FewShotPL#12]
Excuse me, 
After I finished the pretraining of meta-baseline, I got an error when loading the pretrained model in finetune stage.
`RuntimeError: Error(s) in loading state_dict for ProtoNet:
        Missing key(s) in state_dict "classifier.scale_cls".
        Unexpected key(s) in state_dict: "classifier.weight", "classifier.bias".`
It seems that you may have a wrong setting in the file _set_config_meta_baseline_finetune.py_

**Comment by Frankluox** [comment]
Yes. Thanks for reporting the wrong setting. Please set config_dict["load_backbone_only"] in line 23 to True and see if everything goes well.

**Comment by LIUZIJING-CHN** [comment]
Thx, it works.
