### ISSUE TITLE
 How to train PN network to use different ways in training and testing

### ISSUE THREAD

**Issue by tinywaferShark** [Frankluox/FewShotPL#15]
I try to modify the dataset and basemodel in their init function.
But it's a pity that I can't use these hyperparameters like val_ways train_ways.
How to modify the code to implement this function? I haven't used Lighting torch before.

**Comment by Frankluox** [comment]
Since the training and testing are separated, a simple method is to use any number of ways in the config file for training, and then use another number of ways in the config file for testing. Any further questions are welcome.

**Comment by tinywaferShark** [comment]
This method is indeed feasible, but if the number of classes used in training exceeds the number of classes in all val, an error will be reported.
For example, in a MiniImagenet dataset, an error will be reported if ways=20 is set.

**Comment by Frankluox** [comment]
Hi, I have changed all the code to make it possible to separate ways in train, val and test. Now please find three different hyperparameters train_way, val_way and test_way in the config file (I mainly modified base_module.py and few_shot_datamodule.py). Please see if this meets your requirement.

**Comment by Frankluox** [comment]
Closed after one month of inactivity.
