### ISSUE TITLE
The link to the miniImageNet data mentioned in your ReadMe does not work.

### ISSUE THREAD

**Issue by Deepayan137** [Frankluox/FewShotPL#17]
Hello!! The link to your miniImageNet dataset mentioned in the ReadMe seems to be invalid. I would be grateful if you could provide the correct link.

**Comment by Frankluox** [comment]
Sorry, the link was down. Since I am busy these days, please refer to miniImageNet dataset (the version with original images ) in other repos of few-shot learning.

**Comment by Deepayan137** [comment]
Thank you. I will do the needful.
