### ISSUE TITLE
How to train PN + CL with miniimagenet ?

### ISSUE THREAD

**Issue by YeLL0W** [Frankluox/FewShotPL#19]
I have trained with PN with set_config_PN.py successfully, but when I tend to train PN + CL with set_config_CL.py, it told me that

> File /LightningFSL/modules/CL.py", line 269, in training_step
    label = torch.unsqueeze(self.label, 0).repeat(self.hparams.train_batch_size_per_gpu, 1).reshape(-1).to(logits_PN.device)
AttributeError: 'NoAV_CL' object has no attribute 'label'

and it's failed.

**Comment by Frankluox** [comment]
Sorry for the late reply. I do not want to maintain this repo anymore. I also do not recommend using the lightning code in this repo, which is out of date and now has limited values. The research on traditional few-shot learning is also not recommended.
