### ISSUE TITLE
SOC

### ISSUE THREAD

**Issue by tyler-tan** [Frankluox/FewShotPL#20]
您好，非常感谢您提出COSOC这样优秀的方法并且提供代码，但我在学习SOC.py文件中的代码时，发现了几处我不太理解的地方，望解答：
1.97行的features_focus.append(count * features_avg)中，是否应该加入的是 features_train而不是features_avg。
2.115行的temp[q, w, e, :, :] = sim[
                    q, w, e, torch.arange(sim.size(3)) != idx_1[q, w, e, idx_2[q, w, e].item()].item(), torch.arange(
                        sim.size(4)) != idx_2[q, w, e].item()]代码，貌似没有起到将所选行和列去除的功效，而是起到了复制对角线元素的作用？？？不太理解您在此处的原本意义。望解答，谢谢

**Comment by Frankluox** [comment]
您好，两年前写的代码我自己也不太懂了。。不好意思，建议不用再care
