### ISSUE TITLE
Many of the links provided are not working

### ISSUE THREAD

**Issue by Sandy-program** [Frankluox/FewShotPL#21]
Hello author, your experiment has achieved very good results in the field of few shot  image classification. I am very interested in your project, but I find that many links you provided are invalid. Could you please deal with them when you are free, such as the data set links of pre-trained model and miniImageNet-new(in COSOC)?

**Comment by Frankluox** [comment]
I am so sorry that all of the data are saved in one of my previous computers, but the computer has been broken and I cannot fix it. I do not recommend using this repo anymore since it is out of date (in fact, the whole few-shot image classification field is out of date).
