### ISSUE TITLE
The manual data in COSOC.

### ISSUE THREAD

**Issue by skingorz** [Frankluox/FewShotPL#3]
I'm very interested in your work published on NIPS about the influence of background on FSL. It's time-consuming to crop the image manually. Will you open source the related data in the future?

**Comment by Frankluox** [comment]
Here is the data: https://1drv.ms/u/s!AkYSH77Z8H6qc5nj2gyXURV4XuU?e=cnUVvQ

**Comment by skingorz** [comment]
> Here is the data: https://1drv.ms/u/s!AkYSH77Z8H6qc5nj2gyXURV4XuU?e=cnUVvQ

Thank you!
