### ISSUE TITLE
About pretrained models

### ISSUE THREAD

**Issue by Taylorfire** [Frankluox/FewShotPL#6]
I follow the general guide and want to train and test COSOC on miniImageNet. But I am not certain about the pretrained model you provide in the chart. Is the pretrained model used for training a examplar or just the result of a trained examplar (means it can be used for running COS algorithm)?

**Comment by Frankluox** [comment]
Hi, the exemplar needs to be trained from scratch, and the file Exemplar.ckpt is the result (as well as all other files).

**Comment by Taylorfire** [comment]
I see, thanks for your prompt reply ！
