### ISSUE TITLE
How can I cite this code base in my paper?

### ISSUE THREAD

**Issue by skingorz** [Frankluox/FewShotPL#8]
How can I cite this code base in my paper? Could you provide the corresponding bib?

**Comment by Frankluox** [comment]
I think you can cite the NeurIPS paper instead. :)
@inproceedings{COSOC,
  title={Rectifying the Shortcut Learning of Background for Few-Shot Learning},
  author={Luo, Xu and Wei, Longhui and Wen, Liangjian and Yang, Jinrong and Xie, Lingxi and Xu, Zenglin and Tian, Qi},
  booktitle={Advances in Neural Information Processing Systems},
  year={2021}
}

**Comment by skingorz** [comment]
ok
